package com.LiteTravel.hotel.pojo;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

@Table(name = "travel_hotel_orders")
public class HotelOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.order_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.hotel_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private Integer hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.user_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.days
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private Integer days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.status
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.createDate
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.payDate
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private Date paydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.confirmDate
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private Date confirmdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_hotel_orders.total
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private BigDecimal total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.order_id
     *
     * @return the value of travel_hotel_orders.order_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.order_id
     *
     * @param orderId the value for travel_hotel_orders.order_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.hotel_id
     *
     * @return the value of travel_hotel_orders.hotel_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.hotel_id
     *
     * @param hotelId the value for travel_hotel_orders.hotel_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.user_id
     *
     * @return the value of travel_hotel_orders.user_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.user_id
     *
     * @param userId the value for travel_hotel_orders.user_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.days
     *
     * @return the value of travel_hotel_orders.days
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.days
     *
     * @param days the value for travel_hotel_orders.days
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.status
     *
     * @return the value of travel_hotel_orders.status
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.status
     *
     * @param status the value for travel_hotel_orders.status
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.createDate
     *
     * @return the value of travel_hotel_orders.createDate
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.createDate
     *
     * @param createdate the value for travel_hotel_orders.createDate
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.payDate
     *
     * @return the value of travel_hotel_orders.payDate
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.payDate
     *
     * @param paydate the value for travel_hotel_orders.payDate
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.confirmDate
     *
     * @return the value of travel_hotel_orders.confirmDate
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public Date getConfirmdate() {
        return confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.confirmDate
     *
     * @param confirmdate the value for travel_hotel_orders.confirmDate
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setConfirmdate(Date confirmdate) {
        this.confirmdate = confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_hotel_orders.total
     *
     * @return the value of travel_hotel_orders.total
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_hotel_orders.total
     *
     * @param total the value for travel_hotel_orders.total
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
}