package com.LiteTravel.Hotel.pojo;

import javax.persistence.Table;

@Table(name = "travel_room_bed")
public class RoomBedMap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_room_bed.room_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_room_bed.bed_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private Integer bedId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_room_bed.bed_count
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    private Integer bedCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_room_bed.room_id
     *
     * @return the value of travel_room_bed.room_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_room_bed.room_id
     *
     * @param roomId the value for travel_room_bed.room_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_room_bed.bed_id
     *
     * @return the value of travel_room_bed.bed_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public Integer getBedId() {
        return bedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_room_bed.bed_id
     *
     * @param bedId the value for travel_room_bed.bed_id
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setBedId(Integer bedId) {
        this.bedId = bedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_room_bed.bed_count
     *
     * @return the value of travel_room_bed.bed_count
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public Integer getBedCount() {
        return bedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_room_bed.bed_count
     *
     * @param bedCount the value for travel_room_bed.bed_count
     *
     * @mbg.generated Mon Feb 24 17:39:19 CST 2020
     */
    public void setBedCount(Integer bedCount) {
        this.bedCount = bedCount;
    }
}